export enum Field {

    SYSTEM = "SYSTEM",
    INFO = "INFO",
    ID = "ID",
    EMAIL = "EMAIL",
    PASSWORD="PASSWORD",
    SCHEDULING_HOUR = "SCHEDULING_HOUR",
    SCHEDULING_TIME_DATE = "SCHEDULING_DATE",
    SCHEDULING_TIME_AVAILABLE_COLLABORATOR_NUMBER = "AVAILABLE_COLLABORATOR_NUMBER",
    SCHEDULING_TIME_BEGIN_SCHEDULING_DATE = "END_SCHEDULING_DATE",
    SCHEDULING_TIME_END_SCHEDULING_DATE = "END_SCHEDULING_DATE",
    SCHEDULING_TIME_END_WORK_TIME = "END_WORK_TIME",
    SCHEDULING_TIME_BEGIN_LUNCH_TIME = "BEGIN_LUNCH_TIME",
    SCHEDULING_TIME_END_LUNCH_TIME = "END_LUNCH_TIME",
    SCHEDULING_BEGIN_CREATION_DATE = "BEGIN_CREATION_DATE",
    SCHEDULING_END_CREATION_DATE = "END_CREATION_DATE",
    SCHEDULING_BEGIN_SCHEDULING_TIME = "BEGIN_SCHEDULING_TIME",
    SCHEDULING_END_SCHEDULING_TIME = "BEGIN_SCHEDULING_TIME",
    SCHEDULING_TIME_END_SCHEDUULING_TIME = "END_WORK_TIME",
    SCHEDULING_BEGIN_SCHEDULING_TIME_INAVLID = "BEGIN_SCHEDULING_TIME",
    SCHEDULING_END_SCHEDULING_TIME_INAVLID = "END_SCHEDULING_TIME",



}