export enum MessageTemplateFixedIdEnum {

  // USER 
  CREATE_NEW_USER_SUBJECT = "CREATE_NEW_USER_SUBJECT",
  CREATE_NEW_USER_BODY = "CREATE_NEW_USER_BODY",

  RESET_PASSWORD_SUBJECT = "RESET_PASSWORD_SUBJECT",
  RESET_PASSWORD_BODY = "RESET_PASSWORD_BODY",

  // SCHEDULING
  NEW_SCHEDULING_SUBJECT = "NEW_SCHEDULING_SUBJECT",
  NEW_SCHEDULING_BODY = "NEW_SCHEDULING_BODY",


}